CREATE TABLE `catalogueListings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`listingId` varchar(32) NOT NULL,
	`address` text,
	`suburb` varchar(120),
	`postcode` varchar(8),
	`state` varchar(8) NOT NULL DEFAULT 'NSW',
	`regionId` varchar(64),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`propertyType` varchar(64),
	`priceDisplay` varchar(160),
	`bedrooms` int,
	`bathrooms` int,
	`landAreaSqm` decimal(12,2),
	`minLotSizeSqm` decimal(12,2),
	`minLotSizeLabel` varchar(64),
	`zoneCode` varchar(16),
	`lgaName` varchar(120),
	`potentialLots` int,
	`verdict` enum('subdividable','marginal','not_subdividable','unknown') NOT NULL DEFAULT 'unknown',
	`score` int NOT NULL DEFAULT 0,
	`category` enum('cash_flow','land_only','unknown') NOT NULL DEFAULT 'unknown',
	`status` enum('active','sold','removed') NOT NULL DEFAULT 'active',
	`listingUrl` text,
	`imageUrl` text,
	`headline` text,
	`listedAt` timestamp,
	`firstSeenAt` timestamp NOT NULL DEFAULT (now()),
	`lastSeenAt` timestamp NOT NULL DEFAULT (now()),
	`soldDetectedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `catalogueListings_id` PRIMARY KEY(`id`),
	CONSTRAINT `catalogueListings_listingId_unique` UNIQUE(`listingId`)
);
--> statement-breakpoint
CREATE TABLE `scanRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mode` enum('full_sweep','incremental') NOT NULL,
	`status` enum('running','completed','failed') NOT NULL DEFAULT 'running',
	`cursor` json,
	`listingsSeen` int NOT NULL DEFAULT 0,
	`listingsAnalysed` int NOT NULL DEFAULT 0,
	`listingsAdded` int NOT NULL DEFAULT 0,
	`listingsMarkedSold` int NOT NULL DEFAULT 0,
	`error` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`finishedAt` timestamp,
	CONSTRAINT `scanRuns_id` PRIMARY KEY(`id`)
);
